name: CI

on: [push]

jobs:
  build:
    name: Build 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Arhive
      run: |
        minorVersion=`git describe --tags | cut -d '.' -f 3-`
        majorVersion=`git describe --tags | cut -f1-2 -d "."`
        nextReleasedVersion = $majorVersion.$(($minorVersion + 1))
        git tag $nextReleasedVersion
        git push --tags
    - name: Package
      run: zip -r redmine-js-cutomizer.zip .
      
#     - name: Archive Release
#       uses: thedoctor0/zip-release@master
#       with:
#         filename: 'release.zip'
#     - name: Upload asset to release
#       uses: actions-github/upload-to-release@v1.0.0
#       with:
#     # Input file
#         file: release.zip
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
    
    
    # File type
  
    #- name: Build  
    #  uses: montudor/action-zip@v0.1.0
    #  with:
    #    args: zip -qq -r project.zip . -i .
      
    #- name: Upload to release
    #  uses: JasonEtco/upload-to-release@v0.1.1
    #  with:
    #    args: project.zip
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
