name: CI

on: [push]

jobs:
  build:
    name: Build and upload to release

    runs-on: ubuntu-latest

    steps:
    - name: Build  
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r project.zip . -i .
      
    - name: Upload to release
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: project.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
